#include "PluginEditor.h"
ChisescraistVOXAudioProcessorEditor::ChisescraistVOXAudioProcessorEditor(ChisescraistVOXAudioProcessor&x):AudioProcessorEditor(&x),p(x){
 setLookAndFeel(&lnf);setSize(760,520);knob(input,il,"INPUT");knob(drive,dl,"DRIVE");knob(dark,dkl,"DARK");knob(comp,cl,"COMP");knob(delay,dell,"DELAY");knob(reverb,rl,"REVERB");knob(output,ol,"OUTPUT");
 character.addItem("CLEAN",1);character.addItem("DARK",2);character.addItem("RADIO",3);addAndMakeVisible(character);button(st);button(th);button(fi);
 for(auto*b:{&q4,&q8,&q16,&q32})addAndMakeVisible(*b);
 auto setRate=[this](juce::TextButton&b,int i){b.onClick=[this,i]{if(auto*o=p.apvts.getParameter("stutterRate")){float n=o->convertTo0to1((float)i);o->beginChangeGesture();o->setValueNotifyingHost(n);o->endChangeGesture();}};};
 setRate(q4,0);setRate(q8,1);setRate(q16,2);setRate(q32,3);addAndMakeVisible(bpm);
 auto&s=p.apvts;ia=std::make_unique<SA>(s,"input",input);da=std::make_unique<SA>(s,"drive",drive);dka=std::make_unique<SA>(s,"dark",dark);ca=std::make_unique<SA>(s,"comp",comp);dela=std::make_unique<SA>(s,"delay",delay);ra=std::make_unique<SA>(s,"reverb",reverb);oa=std::make_unique<SA>(s,"output",output);sta=std::make_unique<BA>(s,"stutter",st);tha=std::make_unique<BA>(s,"throw",th);fia=std::make_unique<BA>(s,"filter",fi);cha=std::make_unique<CA>(s,"character",character);startTimerHz(10);}
ChisescraistVOXAudioProcessorEditor::~ChisescraistVOXAudioProcessorEditor(){setLookAndFeel(nullptr);}
void ChisescraistVOXAudioProcessorEditor::knob(juce::Slider&s,juce::Label&l,const juce::String&n){s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,68,18);addAndMakeVisible(s);l.setText(n,juce::dontSendNotification);l.setJustificationType(juce::Justification::centred);addAndMakeVisible(l);}
void ChisescraistVOXAudioProcessorEditor::button(juce::TextButton&b){b.setClickingTogglesState(true);addAndMakeVisible(b);}
void ChisescraistVOXAudioProcessorEditor::timerCallback(){bpm.setText(juce::String(p.getHostBpm(),1)+" BPM",juce::dontSendNotification);}
void ChisescraistVOXAudioProcessorEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff0b0b0b));g.setColour(juce::Colours::white);g.setFont(30);g.drawText("CHISESCRAIST VOX",28,20,500,40,juce::Justification::left);g.setColour(juce::Colour(0xff888888));g.setFont(13);g.drawText("REAL-TIME VOCAL FX  •  v0.1",30,58,350,20,juce::Justification::left);}
void ChisescraistVOXAudioProcessorEditor::resized(){int xs[]={35,135,235,335,435,535,635};juce::Slider*k[]={&input,&drive,&dark,&comp,&delay,&reverb,&output};juce::Label*l[]={&il,&dl,&dkl,&cl,&dell,&rl,&ol};for(int i=0;i<7;i++){k[i]->setBounds(xs[i],110,90,100);l[i]->setBounds(xs[i],210,90,20);}character.setBounds(40,275,180,32);st.setBounds(250,272,130,38);th.setBounds(395,272,130,38);fi.setBounds(540,272,130,38);q4.setBounds(40,365,72,34);q8.setBounds(120,365,72,34);q16.setBounds(200,365,72,34);q32.setBounds(280,365,72,34);bpm.setBounds(570,35,150,25);}
