#include "PluginEditor.h"
namespace { const juce::Colour bg(0xff090909),panel(0xff171010),red(0xffff351e),muted(0xff7f3630),white(0xfff9e6df); }
BeatMaxEditor::BeatMaxEditor(BeatMaxProcessor& p):juce::AudioProcessorEditor(&p),processor(p){
 setSize(960,760);
 style.addItemList({"TECH HOUSE","MELODIC HOUSE","AFRO HOUSE","MELODIC TECHNO","AFRO TECHNO"},1);style.setSelectedId(1,juce::dontSendNotification);addAndMakeVisible(style);
 style.onChange=[this]{processor.style=style.getSelectedId()-1;};
 length.addItemList({"4 BARS","8 BARS","16 BARS"},1);length.setSelectedId(1,juce::dontSendNotification);addAndMakeVisible(length);
 length.onChange=[this]{processor.bars=(length.getSelectedId()==1?4:length.getSelectedId()==2?8:16);processor.generate();repaint();};
 auto configureSlider=[this](juce::Slider& slider,double min,double max,double value,const juce::String& suffix){slider.setSliderStyle(juce::Slider::LinearHorizontal);slider.setTextBoxStyle(juce::Slider::TextBoxRight,false,48,20);slider.setRange(min,max,1);slider.setValue(value,juce::dontSendNotification);slider.setTextValueSuffix(suffix);addAndMakeVisible(slider);};
 configureSlider(bpm,80,170,processor.bpm," BPM");bpm.onValueChange=[this]{processor.bpm=(int)bpm.getValue();};
 configureSlider(swing,0,50,12," %");swing.onValueChange=[this]{processor.swing=(float)(swing.getValue()/100.0);};
 configureSlider(variation,0,100,35," %");variation.onValueChange=[this]{processor.variation=(float)(variation.getValue()/100.0);};
 for(auto* button:{&generate,&exportFull,&dragFull,&exportAll,&preview})addAndMakeVisible(*button);
 generate.onClick=[this]{processor.generate();repaint();};exportFull.onClick=[this]{exportMidi(-1);};dragFull.onClick=[this]{dragMidi(-1);};
 exportAll.onClick=[this]{juce::FileChooser chooser("Elegir carpeta para los MIDI individuales",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory));if(chooser.browseForDirectory()){auto folder=chooser.getResult();for(int i=0;i<9;++i)if(processor.lanes[(size_t)i].enabled)processor.writeMidi(folder.getChildFile("BEATMAX_"+processor.lanes[(size_t)i].name.replaceCharacter(' ','_')+".mid"),i);}};
 preview.onClick=[this]{processor.preview=!processor.preview;preview.setButtonText(processor.preview?"PREVIEW ON":"PREVIEW OFF");};
 const juce::StringArray soundOptions[]={ {"DEEP","PUNCHY","ANALOG","TIGHT"},{"DRY","WIDE","VINTAGE","LAYERED"},{"TIGHT","ANALOG","ELECTRONIC"},{"SHORT","CRISP","SOFT","METALLIC"},{"AIRY","BRIGHT","VINTAGE"},{"SOFT","ORGANIC","BRIGHT"},{"WOOD","DRY","METALLIC"},{"CONGA","BONGO","TOM","WOODBLOCK"},{"CONGA","BONGO","TOM","WOODBLOCK"} };
 for(int i=0;i<9;++i){auto& c=controls[(size_t)i];c.enable.setButtonText("");c.enable.setToggleState(processor.lanes[(size_t)i].enabled,juce::dontSendNotification);addAndMakeVisible(c.enable);c.enable.onClick=[this,i]{processor.lanes[(size_t)i].enabled=controls[(size_t)i].enable.getToggleState();repaint();};
 c.lock.setButtonText("LOCK");addAndMakeVisible(c.lock);c.lock.onClick=[this,i]{processor.lanes[(size_t)i].locked=controls[(size_t)i].lock.getToggleState();};
 c.sound.addItemList(soundOptions[i],1);c.sound.setSelectedId(1,juce::dontSendNotification);addAndMakeVisible(c.sound);c.sound.onChange=[this,i]{processor.lanes[(size_t)i].sound=controls[(size_t)i].sound.getSelectedId()-1;};
 c.level.setSliderStyle(juce::Slider::LinearHorizontal);c.level.setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);c.level.setRange(0,1,0.01);c.level.setValue(0.65);addAndMakeVisible(c.level);c.level.onValueChange=[this,i]{processor.lanes[(size_t)i].level=(float)controls[(size_t)i].level.getValue();};
 addAndMakeVisible(c.regenerate);c.regenerate.onClick=[this,i]{processor.generate(i);repaint();};addAndMakeVisible(c.drag);c.drag.onClick=[this,i]{dragMidi(i);};
 }
 startTimerHz(4);
}
void BeatMaxEditor::refresh(){style.setSelectedId(processor.style+1,juce::dontSendNotification);length.setSelectedId(processor.bars==4?1:processor.bars==8?2:3,juce::dontSendNotification);bpm.setValue(processor.bpm,juce::dontSendNotification);swing.setValue(processor.swing*100,juce::dontSendNotification);variation.setValue(processor.variation*100,juce::dontSendNotification);preview.setButtonText(processor.preview?"PREVIEW ON":"PREVIEW OFF");for(int i=0;i<9;++i){auto& c=controls[(size_t)i];const auto& l=processor.lanes[(size_t)i];c.enable.setToggleState(l.enabled,juce::dontSendNotification);c.lock.setToggleState(l.locked,juce::dontSendNotification);c.sound.setSelectedId(l.sound+1,juce::dontSendNotification);c.level.setValue(l.level,juce::dontSendNotification);}}
void BeatMaxEditor::timerCallback(){repaint(juce::Rectangle<int>(20,185,920,465));}
void BeatMaxEditor::resized(){style.setBounds(115,91,168,28);length.setBounds(365,91,100,28);bpm.setBounds(505,91,190,28);swing.setBounds(115,130,185,28);variation.setBounds(395,130,185,28);preview.setBounds(760,125,176,34);
 for(int i=0;i<9;++i){int y=199+i*49;auto& c=controls[(size_t)i];c.enable.setBounds(23,y+9,23,23);c.sound.setBounds(133,y+7,127,28);c.level.setBounds(269,y+8,82,27);c.lock.setBounds(354,y+7,69,28);c.regenerate.setBounds(758,y+7,81,28);c.drag.setBounds(846,y+7,91,28);}
 generate.setBounds(22,668,180,39);exportFull.setBounds(209,668,177,39);dragFull.setBounds(393,668,180,39);exportAll.setBounds(580,668,180,39);
}
void BeatMaxEditor::paint(juce::Graphics& g){g.fillAll(bg);g.setColour(panel);g.fillRoundedRectangle(12.f,12.f,936.f,733.f,9.f);g.setColour(red);g.drawRoundedRectangle(12.f,12.f,936.f,733.f,9.f,1.5f);g.setFont(juce::Font(juce::FontOptions(29.f,juce::Font::bold)));g.drawText("BEATMAX",24,18,350,44,juce::Justification::centredLeft);g.setFont(juce::Font(juce::FontOptions(12.f)));g.setColour(white);g.drawText("CHISESCRAIST AUDIO  |  HOUSE DRUM & PERCUSSION GENERATOR",25,58,620,20,juce::Justification::centredLeft);
 g.setColour(red);g.setFont(juce::Font(juce::FontOptions(12.f,juce::Font::bold)));g.drawText("STYLE",26,92,83,27,juce::Justification::centredLeft);g.drawText("LENGTH",298,92,64,27,juce::Justification::centredLeft);g.drawText("BPM",471,92,39,27,juce::Justification::centredLeft);g.drawText("SWING",26,130,83,27,juce::Justification::centredLeft);g.drawText("VARIATION",310,130,83,27,juce::Justification::centredLeft);
 g.setColour(white);g.setFont(juce::Font(juce::FontOptions(11.f)));g.drawText("INSTRUMENT",50,173,83,18,juce::Justification::centredLeft);g.drawText("SOUND",140,173,100,18,juce::Justification::centredLeft);g.drawText("LEVEL",275,173,70,18,juce::Justification::centredLeft);g.drawText("16-STEP GRID  |  CLICK TO EDIT  |  EACH BAR REPEATS",433,173,318,18,juce::Justification::centredLeft);
 const juce::ScopedTryLock guard(processor.lock);if(!guard.isLocked())return;
 for(int i=0;i<9;++i){int y=199+i*49;const auto& lane=processor.lanes[(size_t)i];g.setColour(i%2?juce::Colour(0xff211010):juce::Colour(0xff160b0b));g.fillRoundedRectangle(20.f,(float)y,920.f,43.f,4.f);g.setColour(lane.enabled?white:muted);g.setFont(juce::Font(juce::FontOptions(11.f,juce::Font::bold)));g.drawText(lane.name,49,y+8,80,27,juce::Justification::centredLeft);
 for(int s=0;s<16;++s){juce::Rectangle<float> cell(434.f+s*19.8f,(float)y+11,16.f,21.f);bool active=false;int vel=0;for(const auto& hit:lane.hits)if(hit.step%16==s){active=true;vel=hit.velocity;break;}g.setColour(active?red.withAlpha((float)vel/127.f):juce::Colour(0xff382020));g.fillRoundedRectangle(cell,2.f);if(s%4==0){g.setColour(muted);g.drawLine(cell.getX()-2,(float)y+6,cell.getX()-2,(float)y+37,0.8f);}}
 }
 g.setColour(white);g.setFont(juce::Font(juce::FontOptions(11.f)));g.drawText("DRAG MIDI individual: una pista por instrumento. DRAG FULL: clip conjunto, canal 10, mapeo GM.",23,716,910,18,juce::Justification::centredLeft);
}
void BeatMaxEditor::mouseDown(const juce::MouseEvent& e){auto p=e.getPosition();if(p.x<434||p.x>=751||p.y<199||p.y>=199+9*49)return;int lane=(p.y-199)/49;int step=juce::jlimit(0,15,(int)((p.x-434)/19.8));const juce::ScopedLock guard(processor.lock);auto& l=processor.lanes[(size_t)lane];if(l.locked)return;bool found=false;for(auto it=l.hits.begin();it!=l.hits.end();){if(it->step%16==step){it=l.hits.erase(it);found=true;}else ++it;}if(!found)for(int bar=0;bar<processor.bars;++bar)l.hits.push_back({bar*16+step,l.midiNote,105});repaint();}
void BeatMaxEditor::exportMidi(int lane){juce::FileChooser chooser("Guardar MIDI",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile(lane<0?"BEATMAX_FULL.mid":"BEATMAX_"+processor.lanes[(size_t)lane].name.replaceCharacter(' ','_')+".mid"),"*.mid");if(chooser.browseForFileToSave(true))processor.writeMidi(chooser.getResult().withFileExtension("mid"),lane);}
juce::File BeatMaxEditor::dragFile(int lane){auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ChisesCraist_BeatMax_Drag");folder.createDirectory();auto f=folder.getChildFile(lane<0?"BEATMAX_FULL.mid":"BEATMAX_"+processor.lanes[(size_t)lane].name.replaceCharacter(' ','_')+".mid");processor.writeMidi(f,lane);return f;}
void BeatMaxEditor::dragMidi(int lane){auto f=dragFile(lane);if(f.existsAsFile())juce::DragAndDropContainer::performExternalDragDropOfFiles(juce::StringArray{f.getFullPathName()},false,this,[]{});}
juce::AudioProcessorEditor* BeatMaxProcessor::createEditor(){return new BeatMaxEditor(*this);}
